### ISSUE TITLE
Remove U/FL connecting CLK_IN_{P,N}<0>

### ISSUE THREAD

**Issue by DavidCussans** [uob-hep-cad/uob-hep-pc065#14]
CLK_IN_{P,N}<0>not used any more

**Comment by oxfpete** [comment]
Not sure where this located?

**Comment by oxfpete** [comment]
Have removed the sockets PX1/PX2 which had that net going nowhere. My apologies didn't recognise the connector type "U/FL" immediately.

Done.

**Comment by DavidCussans** [comment]
Schematic change looks good.
