### ISSUE TITLE
Connect SI, CK,EN lines of U1 fanout ( cdclvd110 ) to FMC_LA_*

### ISSUE THREAD

**Issue by DavidCussans** [uob-hep-cad/uob-hep-pc065#15]
We want the ability to switch between the on-board crystal and the clock coming through the FMC connector.

So, connect  SI, CK and EN lines of U1 ( cdclvd110 )  to FPGA pins ( FMC_LA_* ). 

Leave pull-down resistors - just in case we need somewhere to tack on bodge wiring.

**Comment by oxfpete** [comment]
Done.

FMC_LA_P(26) > CDCLVD110_SI
FMC_LA_P(29) > CDCLVD110_CK
FMC_LA_P(32) > CDCLVD110_EN

4K7 pull downs remain on U1 page of schematic

**Comment by DavidCussans** [comment]
Schematic change looks good.
