### ISSUE TITLE
Remove CLK_{RST,INTR,LOL}_B and CDR_{LOS,LOL} from IC23 and replace with connection to side-launch LEDs next to SFPs

### ISSUE THREAD

**Issue by DavidCussans** [uob-hep-cad/uob-hep-pc065#17]
Remove CLK_{RST,INTR,LOL}_B and CDR_{LOS,LOL} from IC23 and replace with connection to side-launch LEDs  next to SFPs
to allow for status of LEDs to be indicated.

Example LED: https://uk.farnell.com/wurth-elektronik/155060ys73200/led-yellow-150mcd-589nm/dp/3408654

(any side-launch LED will do ).

**Comment by oxfpete** [comment]
Signals removed, part creation in progress.

**Comment by oxfpete** [comment]
Completed. Query net names for the LEDs added?

**Comment by DavidCussans** [comment]
Schematic change looks good.
PCB layout looks good.
