### ISSUE TITLE
Connect the  SFP control/status and LED lines directly to the FPGA via level shifters

### ISSUE THREAD

**Issue by DavidCussans** [uob-hep-cad/uob-hep-pc065#37]
Connect up the SFP control/status and LED lines directly to the FPGA via level shifters, rather than via the I2C io-extenders IC10 , IC23. ( SFP_TX_DISABLE* , SFP_FAULT* , SFP_LOS* , I2CLED* ) 

I was thinking of using the sn74avc8t245 as a level translator.  

I took the CERN library component, which only has the TSSOP package and saved it to our local Bristol libraries as sn74axc8t245  (to avoid name clashes , but they are pin compatible so this is a BoM fudge at worst). I attach Zip archives containing the schematic symbol and the footprint/pads for the VQFN package.  

[74axc8t245.zip](https://github.com/uob-hep-cad/uob-hep-pc065/files/15252338/74axc8t245.zip)
[VQFN_AllegroPCBFootprint.zip](https://github.com/uob-hep-cad/uob-hep-pc065/files/15252345/VQFN_AllegroPCBFootprint.zip)

**Comment by oxfpete** [comment]
Done.
