### ISSUE TITLE
Replace Si5345 clock generator with a low-jitter fanout.

### ISSUE THREAD

**Issue by DavidCussans** [uob-hep-cad/uob-hep-pc065#4]
Chaining PLLs increases jitter between endpoints

--> Replace Si5345 clock generator with a low-jitter fanout. One input to clock from AFC. Other input from a 250MHz TCXO (same family but different frequency as used on rest of DTS boards)

**Comment by oxfpete** [comment]
Done but have left notes on schematic sheet. Nothing critical just want confirmation is safe to delete bus definitions.

**Comment by DavidCussans** [comment]
Which bus definitions?

If they aren’t used, then , yes. ( It would be good not to have signal names that aren’t connected to anything cluttering up the schematic. I would also be good to run the schematic check tool to check for unused/unconnected nets )

Thanks!

**Comment by DavidCussans** [comment]
Schematic changes look good.
