### ISSUE TITLE
Make the resistor pulling down PRSNT_L DNF

### ISSUE THREAD

**Issue by DavidCussans** [uob-hep-cad/uob-hep-pc065#7]
For some reason the JTAG chain through the FMC doesn't work. So, fitting the resistor that pulls down PRSNT_L breaks JTAG chain.

---> make the resistor pulling down PRSNT_L "do not fit" 

(i.e. this is a BoM-only change)

**Comment by oxfpete** [comment]
done.

**Comment by DavidCussans** [comment]
Schematic change looks good.
