### ISSUE TITLE
Increase outer diameter of M2.5 fixing holes to 6.5mm

### ISSUE THREAD

**Issue by DavidCussans** [uob-hep-cad/uob-hep-pc065#8]
Outer diameter of M2.5 fixing holes on FIB is too small and we have to use nylon washers to avoid shorting tracks

---> Increase outer diameter of M2.5 fixing holes to 6.5mm

**Comment by oxfpete** [comment]
done.

**Comment by DavidCussans** [comment]
Great! Once checked we can close this issue.

**Comment by DavidCussans** [comment]
Looks like package KO hasn't been increased. Don't worry about SFP cages.

**Comment by DavidCussans** [comment]
Layout looks OK. C4 etc. moved away
