### ISSUE TITLE
Add 3A fuses on 3.3V and VAUX (2.5V ) lines

### ISSUE THREAD

**Issue by DavidCussans** [uob-hep-cad/uob-hep-pc065#9]
In order to ease the process of getting safety approval from FNAL, add 3A fuses on 3.3V and 2.5V

**Comment by oxfpete** [comment]
e.g. BournsSMD Non Resettable Fuse 3A, 32V dc
Bourns

RS Stock No.:
    692-5003
Mfr. Part No.:
    SF-0603S300-2

**Comment by oxfpete** [comment]
Done point 10 for more detail

**Comment by DavidCussans** [comment]
Checked on schematic. Good
Checked on PCB layout ( _18.brd ). Good
